// const ERROR_CODE = 400;
const CAST_ERROR_ERROR_CODE = 400;
const VALIDATION_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INTERNAL_SERVER_ERROR_CODE = 500;
const FORBIDDEN_ERROR_CODE = 403;
const CONFLICT_ERROR_CODE = 409;
const DUPLICATE_ERROR_CODE = 11000;
const UNAUTHORIZED_ERROR_CODE = 401;

// export variables

module.exports = {
  CAST_ERROR_ERROR_CODE,
  VALIDATION_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  DUPLICATE_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
};
